# Generated by Django 6.0.2 on 2026-02-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("datetime", models.DateTimeField()),
                ("temperature", models.FloatField()),
                ("precipitation", models.FloatField()),
            ],
            options={
                "verbose_name": "Weather Record",
                "verbose_name_plural": "Weather Records",
                "ordering": ["datetime"],
            },
        ),
    ]
